### ISSUE TITLE
Animations module broken once again

### ISSUE THREAD

**Issue by rland93** [rland93/rrt_pathplanner#13]
```python
Traceback (most recent call last):
  File "rrtpp/anim.py", line 200, in <module>
    anim = dyn_env_anim.make_animation(worlds)
  File "rrtpp/anim.py", line 188, in make_animation
    results = self.simulate_dynamic_goals(worlds)
  File "rrtpp/anim.py", line 91, in simulate_dynamic_goals
    T, gv = self.rrtobj.make(current_position, xgoal)
  File "/home/ms/prg/rrt_pathplanner/rrtpp/rrt.py", line 512, in make
    vgoal, i = self.lc2goal(xgoal, vcosts, points)
AttributeError: 'RRTStarInformed' object has no attribute 'lc2goal'
```

**Comment by rland93** [comment]
Actually, this is a bug with `RRTStarInformed`.

**Comment by rland93** [comment]
resolved, see https://github.com/rland93/rrt_pathplanner/issues/14
